apiVersion: v1
kind: Service
metadata:
  name: {{ include "lk-tnsw.frontend.fullname" . }}
  labels:
    {{- include "lk-tnsw.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "lk-tnsw.frontend.selectorLabels" . | nindent 4 }}
