-- @UP
-- ============================================================================
-- Migration: 000003_insert_seed_data.sql
-- Purpose: Previously seeded baseline test companies/CHAs and HS code/workflow
-- template mapping metadata.
--
-- The company_records/customs_house_agents rows were test-only fixture data,
-- not needed by any real deployment, and moved to `otc company apply` for
-- local dev use. The hs_codes/workflow_template_map rows turned out to be
-- unread by the application and were removed rather than replaced.
--
-- Kept as a no-op stub so the migrator's applied-version history stays intact
-- for environments that already ran it.
-- ============================================================================
-- @DOWN
