-- @UP
-- ============================================================================
-- Migration: 000004_add_npqs_seed_data.sql
-- Purpose: Previously seeded NPQS/trade-export HS codes and workflow template
-- mappings. The hs_codes/workflow_template_map tables turned out to be unread
-- by the application, so this seed data was removed rather than replaced.
-- Kept as a no-op stub so the migrator's applied-version history stays intact
-- for environments that already ran it.
-- ============================================================================
-- @DOWN
