-- @UP
-- ============================================================================
-- Migration: 000007_add_cda_seed_data.sql
-- Purpose: Previously seeded a CDA HS code and workflow template mapping. The
-- hs_codes/workflow_template_map tables turned out to be unread by the
-- application, so this seed data was removed rather than replaced. Kept as a
-- no-op stub so the migrator's applied-version history stays intact for
-- environments that already ran it.
-- ============================================================================
-- @DOWN
