-- @UP
-- ============================================================================
-- Migration: 000008_add_company_seed.sql
-- Purpose: Previously seeded test companies (CDA/FCAU/NPQS/GovTech/PIU/SLTB).
-- This was test-only fixture data, not needed by any real deployment, so it
-- moved to `otc company apply` for local dev use. Kept as a no-op stub so the
-- migrator's applied-version history stays intact for environments that
-- already ran it.
-- ============================================================================
-- @DOWN
