package autogen

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"

	"github.com/OpenNSW/core/taskflow/store"
	"github.com/OpenNSW/nsw-srilanka/internal/autogen"
)

// ExtAgencyRefGen is the extension identifier matching subtask template configs.
const ExtAgencyRefGen = "agency_refnum_generator"

type autogenConfig struct {
	Issuer     string            `json:"issuer,omitempty"`
	AgencyCode string            `json:"agency_code,omitempty"` // Backwards compatibility alias for issuer
	IDType     string            `json:"id_type,omitempty"`
	TargetKey  string            `json:"target_key,omitempty"`
	Params     map[string]string `json:"params,omitempty"`
}

// Extension generates an autogenerated agency reference number and attaches it to the task record data.
type Extension struct {
	seqService autogen.SequenceService
}

// NewExtension builds the extension instance.
func NewExtension(seqService autogen.SequenceService) *Extension {
	return &Extension{seqService: seqService}
}

// Execute resolves the issuer, idType, targetKey and params, requests the reference ID, and populates the task record data.
func (e *Extension) Execute(ctx context.Context, record *store.TaskRecord, payload map[string]any, properties json.RawMessage) error {
	if e.seqService == nil || record == nil {
		return nil
	}

	var cfg autogenConfig
	if len(properties) > 0 {
		_ = json.Unmarshal(properties, &cfg)
	}

	issuer := cfg.Issuer
	if issuer == "" {
		issuer = cfg.AgencyCode
	}
	if issuer == "" {
		// Infer issuer code from TaskType prefix if not explicitly specified (e.g. "fcau_application_review_v1" -> "FCAU")
		if prefix, _, found := strings.Cut(record.TaskType, "_"); found && len(prefix) >= 2 {
			issuer = strings.ToUpper(prefix)
		}
	}

	if issuer == "" {
		return nil
	}

	idType := cfg.IDType
	if idType == "" {
		idType = "application_id"
	}

	targetKey := cfg.TargetKey
	if targetKey == "" {
		targetKey = "reference_number"
	}

	if record.Data == nil {
		record.Data = make(map[string]any)
	}

	// Do not overwrite if a reference number is already generated/present in task data
	if val, exists := record.Data[targetKey]; exists && val != "" {
		return nil
	}

	// Merge parameter sources (cfg.Params override record.Data strings)
	params := make(map[string]string)
	for k, v := range record.Data {
		if strVal, ok := v.(string); ok && strVal != "" {
			params[k] = strVal
		}
	}
	for k, v := range cfg.Params {
		if v != "" {
			params[k] = v
		}
	}

	refNum, err := e.seqService.GetOrGenerateID(ctx, record.RootWorkflowID, record.ParentWorkflowID, issuer, idType, targetKey, params)
	if err != nil {
		slog.ErrorContext(ctx, "autogen extension: failed to generate reference ID", "issuer", issuer, "idType", idType, "error", err)
		return fmt.Errorf("autogen extension: %w", err)
	}

	record.Data[targetKey] = refNum
	slog.InfoContext(ctx, "autogen extension: generated agency reference number", "issuer", issuer, "idType", idType, "refNum", refNum, "taskID", record.TaskID)
	return nil
}
